
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: normal

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/poplar-test.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

